FROM python:3.11.4-slim-buster

WORKDIR /usr/app

RUN pip install -U pip
RUN pip install grpcio-tools==1.57.0
RUN pip install asyncio==3.4.3

COPY grpctutor grpctutor
RUN bash grpctutor/clean_pycache.sh

CMD ["python", "-m", "grpctutor.server"]
